-- Caleb Kugel and Sam Craft
-- Iowa State University
-- Department of Electrical and Computer Engineering
-- File: controlUnit.vhd
-- Description: This file contains the VHDL code for the control unit.

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity controlUnit is
    port(
        Funct : in std_logic_vector(6 downto 0);
        Opcode : in std_logic_vector(6 downto 0);
        RegDst : out std_logic;
        ALUSrc : out std_logic;
        MemtoReg : out std_logic;
        RegWrite : out std_logic;
        MemWrite : out std_logic;
        Jump : out std_logic;
        Branch : out std_logic;
        ALUControl : out std_logic_vector(3 downto 0);
        ALUOp : out std_logic_vector(1 downto 0)
    );
end controlUnit;

architecture Behavioral of controlUnit is
begin
process(Opcode, Funct)
begin
    case Opcode is
        when "000000" => -- R-type instructions
            ALUOp <= "10";
            case Funct is
                when "100000" => -- add
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "0010";
                when "100001" => -- addu
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "0010";
                when "100010" => -- sub
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "0110";
                when "100011" => -- subu
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "0110";
                when "100100" => -- and
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "0000";
                when "100101" => -- or
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "0001";
                when "100110" => -- xor
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "0011";
                when "100111" => -- nor
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "1100";
                when "101010" => -- slt
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "0111";
                when "000000" => -- sll
                    RegDst <= '1';
                    ALUSrc <= '1';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "1000";
                when "000010" => -- srl
                    RegDst <= '1';
                    ALUSrc <= '1';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "1001";
                when "000011" => -- sra
                    RegDst <= '1';
                    ALUSrc <= '1';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "1010";
                when "000100" => -- sllv
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "1000";
                when "000110" => -- srlv
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "1001";
                when "000111" => -- srav
                    RegDst <= '1';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '1';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "1010";
                when "001000" => -- jr
                    RegDst <= '0';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '0';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '1';
                    Branch <= '0';
                    ALUControl <= "0000";
                when others =>
                    RegDst <= '0';
                    ALUSrc <= '0';
                    MemtoReg <= '0';
                    RegWrite <= '0';
                    MemWrite <= '0';
                    MemRead <= '0';
                    Jump <= '0';
                    Branch <= '0';
                    ALUControl <= "0000";
            end case;
        when "001000" => -- addi
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '0';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0010";
            ALUOp <= "00";
        when "001001" => -- addiu
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '0';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0010";
            ALUOp <= "00";
        when "001100" => -- andi
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '0';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0000";
            ALUOp <= "11";
        when "001101" => -- ori
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '0';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0001";
            ALUOp <= "11";
        when "001110" => -- xori
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '0';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0011";
            ALUOp <= "11";
        when "001111" => -- lui
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '0';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "1111";
            ALUOp <= "11";
        when "100011" => -- lw
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '1';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '1';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0010";
            ALUOp <= "00";
        when "101011" => -- sw
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '0';
            RegWrite <= '0';
            MemWrite <= '1';
            MemRead <= '0';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0010";
            ALUOp <= "00";
        when "000100" => -- beq
            RegDst <= '0';
            ALUSrc <= '0';
            MemtoReg <= '0';
            RegWrite <= '0';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '0';
            Branch <= '1';
            ALUControl <= "0110";
            ALUOp <= "01";
        when "000101" => -- bne
            RegDst <= '0';
            ALUSrc <= '0';
            MemtoReg <= '0';
            RegWrite <= '0';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '0';
            Branch <= '1';
            ALUControl <= "0110";
            ALUOp <= "01";
        when "000010" => -- j
            RegDst <= '0';
            ALUSrc <= '0';
            MemtoReg <= '0';
            RegWrite <= '0';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '1';
            Branch <= '0';
            ALUControl <= "0000";
            ALUOp <= "00";
        when "000011" => -- jal
            RegDst <= '0';
            ALUSrc <= '0';
            MemtoReg <= '0';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '1';
            Branch <= '0';
            ALUControl <= "0000";
            ALUOp <= "00";
        when "100000" => -- lb
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '1';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '1';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0010";
            ALUOp <= "00";
        when "100001" => -- lh
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '1';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '1';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0010";
            ALUOp <= "00";
        when "100100" => -- lbu
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '1';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '1';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0010";
            ALUOp <= "00";
        when "100101" => -- lhu
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '1';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '1';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0010";
            ALUOp <= "00";
        when "001010" => -- slti
            RegDst <= '0';
            ALUSrc <= '1';
            MemtoReg <= '0';
            RegWrite <= '1';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0111";
            ALUOp <= "11";
        when others =>
            RegDst <= '0';
            ALUSrc <= '0';
            MemtoReg <= '0';
            RegWrite <= '0';
            MemWrite <= '0';
            MemRead <= '0';
            Jump <= '0';
            Branch <= '0';
            ALUControl <= "0000";
            ALUOp <= "00";
    end case;
end process;
end Behavioral;
